export const masterDataConfig = {
  categories: {
    key: 'categories',
    title: 'Kategori Pekerjaan',
    singular: 'Kategori',
    breadcrumb: 'Kategori',
    endpoint: '/categories',
    routeBase: '/app/admin/master-data/categories',
    createRoute: '/app/admin/master-data/categories/create',
    fields: ['name', 'is_active'],
    columns: [
      { key: 'id', label: 'ID', className: 'col-id' },
      { key: 'name', label: 'Nama', className: 'col-name-wide' },
      { key: 'is_active', label: 'Status', type: 'status', className: 'col-status' },
      { key: 'updated_at', label: 'Terakhir Diubah', className: 'col-updated' },
    ],
    filters: {
      keyword: true,
      status: true,
    },
  },
  subcategories: {
    key: 'subcategories',
    title: 'Subkategori Pekerjaan',
    singular: 'Subkategori',
    breadcrumb: 'Subkategori',
    endpoint: '/subcategories',
    routeBase: '/app/admin/master-data/subcategories',
    createRoute: '/app/admin/master-data/subcategories/create',
    fields: ['category_id', 'unit_id', 'name', 'default_duration', 'default_price', 'description', 'is_active'],
    columns: [
      { key: 'id', label: 'ID', className: 'col-id' },
      { key: 'category_name', label: 'Kategori', className: 'col-category' },
      { key: 'name', label: 'Subkategori', className: 'col-name-wide' },
      { key: 'unit_symbol', label: 'Satuan', className: 'col-symbol' },
      { key: 'default_duration', label: 'Durasi', className: 'col-duration' },
      { key: 'default_price', label: 'Harga Dasar', type: 'currency', className: 'col-price' },
      { key: 'is_active', label: 'Status', type: 'status', className: 'col-status' },
      { key: 'updated_at', label: 'Terakhir Diubah', className: 'col-updated' },
    ],
    filters: {
      keyword: true,
      category: true,
      status: true,
    },
  },
  units: {
    key: 'units',
    title: 'Satuan',
    singular: 'Satuan',
    breadcrumb: 'Satuan',
    endpoint: '/units',
    routeBase: '/app/admin/master-data/units',
    createRoute: '/app/admin/master-data/units/create',
    fields: ['name', 'symbol', 'is_active'],
    columns: [
      { key: 'id', label: 'ID', className: 'col-id' },
      { key: 'name', label: 'Nama', className: 'col-name' },
      { key: 'symbol', label: 'Simbol', className: 'col-symbol' },
      { key: 'is_active', label: 'Status', type: 'status', className: 'col-status' },
      { key: 'updated_at', label: 'Terakhir Diubah', className: 'col-updated' },
    ],
    filters: {
      keyword: true,
      status: true,
    },
  },
  costItems: {
    key: 'costItems',
    title: 'Item Biaya',
    singular: 'Item Biaya',
    breadcrumb: 'Item Biaya',
    endpoint: '/cost-items',
    routeBase: '/app/admin/master-data/cost-items',
    createRoute: '/app/admin/master-data/cost-items/create',
    fields: ['category_id', 'subcategory_id', 'unit_id', 'default_duration', 'default_price', 'description', 'is_active'],
    columns: [
      { key: 'id', label: 'ID', className: 'col-id' },
      { key: 'category_name', label: 'Kategori', className: 'col-category' },
      { key: 'subcategory_name', label: 'Subkategori / Nama Item', className: 'col-name-wide' },
      { key: 'item_name', label: 'Item', className: 'col-name' },
      { key: 'unit_symbol', label: 'Satuan', className: 'col-symbol' },
      { key: 'default_duration', label: 'Durasi', className: 'col-duration' },
      { key: 'default_price', label: 'Harga Dasar', type: 'currency', className: 'col-price' },
      { key: 'is_active', label: 'Status', type: 'status', className: 'col-status' },
    ],
    filters: {
      keyword: true,
      category: true,
      status: true,
    },
  },
  signatories: {
    key: 'signatories',
    title: 'Penandatangan Dokumen',
    singular: 'Penandatangan',
    breadcrumb: 'Penandatangan',
    endpoint: '/signatories',
    routeBase: '/app/admin/master-data/signatories',
    createRoute: '/app/admin/master-data/signatories/create',
    fields: ['name', 'position_title', 'sort_order', 'is_active'],
    columns: [
      { key: 'id', label: 'ID', className: 'col-id' },
      { key: 'signature_image_url', label: 'TTD', type: 'image', className: 'col-signature' },
      { key: 'name', label: 'Nama', className: 'col-name' },
      { key: 'position_title', label: 'Jabatan', className: 'col-name-wide' },
      { key: 'sort_order', label: 'Urutan', className: 'col-duration' },
      { key: 'is_active', label: 'Status', type: 'status', className: 'col-status' },
    ],
    filters: {
      keyword: true,
      status: true,
    },
  },
};

export function getMasterDataConfig(type) {
  return masterDataConfig[type] || null;
}
